[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.pyright]
typeCheckingMode = "strict"

reportImplicitOverride = true
reportImportCycles = "warning"
reportPropertyTypeMismatch = true
reportShadowedImports = "warning"
reportUninitializedInstanceVariable = true
reportUnnecessaryTypeIgnoreComment = "information"
