[tool.pytest.ini_options]
pythonpath = [
  "."
]
testpaths = "tests"

[tool.pyright]
typeCheckingMode = "strict"

reportImplicitOverride = true
reportImportCycles = "warning"
reportPropertyTypeMismatch = true
reportShadowedImports = "warning"
reportUninitializedInstanceVariable = true
reportUnnecessaryTypeIgnoreComment = "information"
