#!/usr/bin/env python

import argparse

from compiler.compiler import get_default_environs, run


def main():
    parser = argparse.ArgumentParser(description="Ryuc Language Compiler")
    parser.add_argument("file", help="Path to the Ryuc source file")
    args = parser.parse_args()

    with open(args.file, "r") as file:
        source = file.read()

    type_env, runtime_env = get_default_environs()
    run(source, type_env, runtime_env)


if __name__ == "__main__":
    main()
